branches:
  # PRs are always built. So we exclude branch builds other than master to prevent double-builds.
  # https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
  only:
    - master

# Job queue; see below for default job settings.
jobs:
# [Job] [Docker] multi-ach: https://www.docker.com/blog/multi-arch-build-what-about-travis/
- name: "Docker"
  language: node_js
  dist: bionic
  sudo: required
  os: linux
  arch: amd64
  # services:
  #   - docker
  before_install:
    - npm install -g npm
    # Install Docker 19.x, not 18
    - curl -fsSL https://get.docker.com | sh
    - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
    - mkdir -p $HOME/.docker
    - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
    - sudo service docker start
    - docker --version
    # Install docker-buildx plugin for cross-architecture compilation.
    - mkdir -p ~/.docker/cli-plugins/
    - curl -fsSL -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker context ls
  install:
    # With a multi-arch build, installing on the host machine first is faster.
    - npm install
    # Create a multi-arch buildx user: https://github.com/docker/buildx/issues/138
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --platform linux/arm64,linux/arm/v7 --name xbuilder --use
    - docker buildx inspect --bootstrap
  script:
    - echo "Building $CI_SEMVER"
    # Pre-build assets; this prevents the multi-arch from running each build in the Dockerfile.
    - npm run build-latest
    # Only the master branch supports a "deploy" step. For others, go ahead and push a dev image.
    - scripts/docker.sh build
  after_success: [] # Override.
  addons:
    apt:
      packages:
        - qemu-user-static # multi-arch build tools
        - icnsutils
        - graphicsmagick
        - gcc-multilib
        - g++-multilib
        - rpm
  deploy:
    skip_cleanup: true # Leave build artifacts in place (don't git clean)
    provider: script
    script: scripts/docker.sh deploy
# [Job] [Linux]
- name: "Linux"
  os: linux
  deploy:
    file:
      - releases/${RELEASE_FILE}-linux-amd64.deb
      - releases/${RELEASE_FILE}-linux-i386.AppImage
      - releases/${RELEASE_FILE}-linux-i386.deb
      - releases/${RELEASE_FILE}-linux.i686.rpm
      - releases/${RELEASE_FILE}-linux-ia32.tar.gz
      - releases/${RELEASE_FILE}-linux-x64.tar.gz
      - releases/${RELEASE_FILE}-linux-x86_64.AppImage
      - releases/${RELEASE_FILE}-linux.x86_64.rpm
# [Job] [OSX]
- name: "OSX"
  os: osx
  osx_image: xcode8.3
  before_install:
  - brew update
  deploy:
    file:
      - output/${PRODUCT_NAME}-${CI_SEMVER}.pkg
# [Job] [Windows]
- name: "Windows"
  os: windows
  deploy:
    file:
      - output/${PRODUCT_NAME} Setup ${CI_SEMVER}.exe

# --------------------------------------------------------------------------------------------------
# Default job settings, when not overwritten by specific jobs.
# --------------------------------------------------------------------------------------------------

dist: trusty
group: travis_latest
os: linux
language: node_js
node_js:
  - "12"

env:
  global:
    - CI_VERSION=`git describe --tags | sed 's/-\(.*\)//'`
    - CI_SEMVER=`./scripts/semver.sh $CI_VERSION`
    - TRAVIS_TAG=$CI_VERSION
    - PRODUCT_NAME=Makerverse
    - RELEASE_NAME="${PRODUCT_NAME} v${CI_VERSION}"
    - RELEASE_FILE="makerverse-${CI_SEMVER}"
    - secure: j7SoxNxs3KBRvvLrEWeZGmsgHRLMwcCvYnNh/F8GeaCnM0U87s9AqHMmV4NNRyDoac7PpqegCYk21nLN4mx1Mj9rs/wvQBnl1LYuetRm7ib9Zq21+cJSIaO2USourexEuivySEuzWqR5pb7bcdAZYhKVzBOStw1k0h2rD0xrbdr91UclcQniiex5bqQ4UIE+cPZVqS5vOPZck9P9GMBmVNM0mrfzqTUkiLUFtTbg9Msz5GIIZzJsHj49EqmYwoN1B7te3IkF6tEVLKKNIJPqYMcGhKLZ5jF9ugxkPYPP1JvAxRftrFdCvmdclwJK6yE5ByMY9YHkXw1NvMQ9rzuI10NBM0inUZUmPZepWvnOh4k0FSeFKReWGeVVciap/W0seqxn99lDGMDXaauz5CKD9tVXwAOZ8H/dZAnPEUSd9xEvl5NtLbi1djvvz6LkdDSj9iGedoLEwcxkueBu/UUWLbm+ALdn1dcH1e37TLPc5amP5fIh/klP2KZtfgKzFn8lW65RyrB+UgVlhwQMyv5cCMKAttE1JyU/6bNXvfa0qbnk5m5weVoUsp5PBbx9IYCj7pgGaqmqqON5AOm+JBDK1sl1T2uHCU3wfKBqES8krTPjP7wNiwCTKr7RqyAVYf8d006G6cuDcYIg5NR+l5zM4tfE3U8NHyFrdy0Iw9WBcGg= # DOCKER_EMAIL
#   - secure: "BAiWc6AblNednsnoh2+3OMW81MVzCQPR0UT3E2/gCdScw8Q9C4a8fC0OpXxJOqHy9JgAL3s5kxZVlAbUhBwXJlarDyQl++Y9aeKjr6J0+iVXu3cSF0cUw+rYbQ41u3dFmF3Sa0K5Lo0uB5XX/ximCX8RzgUJ6B79Jh1ac9FbZrYBth6Ovnsy3Us9VvxB8jXI2St6GJgewmXUo8qlWZKClM79NPBjwpboU09zSGhqQ32JssHUjw/peLt6x4SGV+NsMNgSNELXxVVbBBp7Wp5PNJY8D5vhO703Ka2WLJEebZnE+7r5j1VzLO1/OGrOS9QwVzw/fZEhQYST4NZPMu65bR7VI8jwJN2OjIcUx3yH0JbSXmPtdANofusIozGHKvg7odLTSo3js5crFnDBuoP3ZQ8XNusse2smbyd5snUCb0g9FsEzlQLQZBfcubuW3qY5BZwbCyc2e9WoNOLt4C83rcaFuRER5sK/UG9nSGivIsSKOCJpacdIxmCEvZV8h5YUd/OQqTMbFA2YliaLGt7AsfJrR8W4wy+vB12pVEEg7xPK+TnhzhCK61JGOn/pjVmFjUb0zHgcJEry3C5W+J2TEwKxRIEgkLCL7YP3WnE4c5fcqg2c9B4SHOqReO0KEx5mP0FVlGliW69ZHoUPoEC+VTwVzMJheOTnpzXNh4puh1E=" # GITHUB_TOKEN
#    - secure: "zn6ZQM7LFgFcwFNqcbhBGY9DYZzw3tOa3puTntdcEfnMsp+ikcJSYl8lvTj1TL1rvZIAJfO896Uk79HTyJtv06a9LjpEElaQvkBEtPGnE0fdGWLgK1cl0JBxPNEDicAoYrUV2QkuuwaTtpKeUsnD6XmWSzzpqmZKDLfRyO1xwHyvH4aTvqAhDXM7Hb+Hae4Nk7ZCq5v1CwScu6gdaJMBPdcmWBzAPNnAJYbDilw3fFdfOrxhuTagmmBQFn99iaIRbLR4sTuI/c53NMUS8FJyfistTVVuMOFTSdFvlQ/Ikm6PbIYYIMDp9RetGIJk7IL4U18LpwACzhjc25SvWrQXPI7eiW0H3uD8rGPtR50cBrbxRI/Of7271eqXvtNMzHSsCo0ENQ1qYWoF5OhI4roklAfZjQpdi7Ngg+EPNIgf24vpf0fI9u8caOHxzAYjrwdcXCLTmcu0ANuQMMXP5G7mBZG5/kGzC5cpc11uqwINCU10rVQa7JVNuFNhuT98/c+DSeBY92w9nEsCshG1AKcNjY677FbBdVS+DCPPRjiAfjomT9Ma8VqR/bGCogzaEaA7adUbGLGI9V397QF9gSrzyBP/zjOiYVX1mRjylmEitdQtXF3CXsbhrOOCenDifKHhtnOgXgpObcbwV4B82VhGzDOvTxF2n+QTGhUAA/Okyv8=" # CSC_LINK
#    - secure: "LenBHoTcLW6cF7ML3+dB7JICMzEkawrJHiqFcGSo+hgapB0NCHGUiihr2zrjGSlHmElPiQ2TCnCRmPvOzVfpZswg36D0+1niPgZ+0vfGfPEoPmHhlvIsMPLb7v0lCIeh8z2o9eNbSvnv6NRXS4o5NLlHzM+RhAYARSXvRmFxqCCBn1Sj9pB5TB9NX3mK0Lb3mEJcIgEVFBr/xLiISPUBGFmncHUpxYjZHwxXQXRcGyfOEphLM9tvmEdoILRxM67k035csAIeaLKKPJcMGmO0e/JwZacQN7s3MhD2M8NddhQvWklNjabXAJ0L9Ycujf6rI5RsGcZL2U80HKr0aYRMiVW7/MPMpLARFOUoLfuFAXKkkLHp7Lbb1W6Zftr4yxkrfDXIQsh976HkBj+czr6wGwzBwb39zX4KEm/Yc3TEIxC/kKs9bt+vVW6BG+J41neiDiuIY1D1tRA0OEq0j04zpU6n683ojfYddzFoUWCN+TB3i0HQxWsKTOGKdcQwrJs7xZ4//UzD/vOTHj18SH0nm6ImF2/7q+9wJO646gHWTGTjGFYdupuR402wb3h5vWmGfFRvX6B1QtYImmEwMFnqf2XRwTTSz3niKn2Rt1YUiCP5bEz+Dcr+e+A8Jidt6ZuJEXv5SbykTG4YBmgCuuFT5KRwv08kule7FiUtQ2KD5XE=" # CSC_KEY_PASSWORD


cache:
  directories:
    - $HOME/.electron
    - releases

install: npm install
script:
  - echo "Building $CI_SEMVER (v. $CI_VERSION)"
  - npm run build-latest
after_success:
  - PACKAGE_NAME=`node -e "console.log(require('./src/package.json').name)"`
  - PACKAGE_VERSION=`node -e "console.log(require('./src/package.json').version)"`
  - RELEASE_TAG=${CI_VERSION}
  - echo "$RELEASE_NAME ($RELEASE_FILE)"
  - mkdir -p releases
  - |
    # build:mac-x64
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # https://github.com/electron-userland/electron-builder/issues/398
      security import "scripts/certs/Certum-Code-Signing-CA-SHA2.cer" -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign;
      # https://github.com/electron-userland/electron-osx-sign/issues/83
      # Temporarily Bypass Gatekeeper
      sudo spctl --master-disable;
      sudo spctl --status;
      npm run build:mac-x64;
      ls -al output output/*;
      cp -af "output/${PRODUCT_NAME}-${PACKAGE_VERSION}.dmg" "releases/${RELEASE_FILE}-mac-x64.dmg";
      ls -al releases/*;
    fi
  - |
    # build:linux-ia32
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run build:linux-ia32;
      ls -al output output/*;
      cp -af "output/${PRODUCT_NAME}-${PACKAGE_VERSION}-i386.AppImage" "releases/${RELEASE_FILE}-linux-i386.AppImage";
      cp -af "output/${PACKAGE_NAME}_${PACKAGE_VERSION}_i386.deb" "releases/${RELEASE_FILE}-linux-i386.deb";
      cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}.i686.rpm" "releases/${RELEASE_FILE}-linux.i686.rpm";
      pushd releases;
      ln -sf ../output/linux-ia32-unpacked "${RELEASE_FILE}-linux-ia32";
      tar zcfh "${RELEASE_FILE}-linux-ia32.tar.gz" "${RELEASE_FILE}-linux-ia32";
      rm -f "${RELEASE_FILE}-linux-ia32";
      popd;
      ls -al releases/*;
    fi
  - |
    # build:linux-x64
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run build:linux-x64;
      ls -al output output/*;
      cp -af "output/${PRODUCT_NAME}-${PACKAGE_VERSION}.AppImage" "releases/${RELEASE_FILE}-linux-x86_64.AppImage";
      cp -af "output/${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.deb" "releases/${RELEASE_FILE}-linux-amd64.deb";
      cp -af "output/${PACKAGE_NAME}-${PACKAGE_VERSION}.x86_64.rpm" "releases/${RELEASE_FILE}-linux.x86_64.rpm";
      pushd releases;
      ln -sf ../output/linux-unpacked "${RELEASE_FILE}-linux-x64";
      tar zcfh "${RELEASE_FILE}-linux-x64.tar.gz" "${RELEASE_FILE}-linux-x64";
      rm -f "${RELEASE_FILE}-linux-x64";
      popd;
      ls -al releases/*;
    fi
  - |
    # build:windows
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      npm run build:win-x64;
      ls -al output output/*;
      cp -af "output/${PRODUCT_NAME} Setup ${PACKAGE_VERSION}.exe" "releases/${RELEASE_FILE}.exe";
      ls -al releases/*;
    fi
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - gcc-multilib
      - g++-multilib
      - rpm

deploy:
  provider: releases
  skip_cleanup: true # Keep build artifacts in the releases directory.
  api_key:
    secure: NFvrOvBDkBwvJWANXEbkRtrFE0msZF+269Q4VHWL44izsIF/uTooIPt5FlMBvsroiDunwA6Zs/kX8Nnrf/D1zePybNu9zf8JarJuCzZuu80pWSn2aJQHCqH6mKkprSa6BoqxnptJG7Qdr0e16FaSOiDNE68DRhFYztlLZynf4EdD6k40UkP0k+6+v1Wg6qkNNykexP6SZDOzDBTyOLH3KVYvQdTaaiNL6+B1/HYWVF+D+QwGQVp2/k7FDUkaPJMY+1FLmjGuu/5Snl6I9+HqOEkS0zyrob/9DDZx158KhrfnTfx4IKmACA9lGo1eVFb1ZngupA7VYp329kHd7FVYWFbY1lcc2FdBP74xhilzJ4S1wtvDL6FTRbwTai0B7/c0Tsad31e2/2zucldv7Xh2UAzeCv4SPyihFA7cMpzqXncRH9N/JTTArspn9fFXbGsvU1Xo+0GppMHO0PQf77vjUoT7v6wPyE5OYcd9n1/xrTNTX9mttBF864qYEi8gGdZXaIN5ziaVvmaeYXOFuFww+hmRFGuBlNGueTdsHndAKW8oxPKjcQziiTpjuoWokXjp7zg2UUp9F5azihHo1whPmjNNnzfC8Vu2OHgXb3Nj2ugm1NXMRhTKyRt6Lsa8rKL8ZW8J3WpD65Jcm0Wq42q9JfOOgVn/+vf0olKu5wGT0rc=
  overwrite: true
  name: "[CI] $RELEASE_NAME"
  prerelease: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    branch: master
