# Job queue; see below for default job settings.
jobs:
# [Job] [Docker] multi-ach: https://www.docker.com/blog/multi-arch-build-what-about-travis/
- name: "Docker"
  language: bash
  dist: bionic
  sudo: required
  os: linux
  arch: amd64
  # services:
  #   - docker
  before_install:
    # Install Docker 19.x, not 18
    - curl -fsSL https://get.docker.com | sh
    - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
    - mkdir -p $HOME/.docker
    - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
    - sudo service docker start
    - docker --version
    # Install docker-buildx plugin for cross-architecture compilation.
    - mkdir -p ~/.docker/cli-plugins/
    - curl -fsSL -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker context ls
  install:
    # Create a multi-arch buildx user: https://github.com/docker/buildx/issues/138
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --platform linux/arm64,linux/arm/v7 --name xbuilder --use
    - docker buildx inspect --bootstrap
  script: scripts/docker.sh build
  after_success: [] # Override.
  addons:
    apt:
      packages:
        - qemu-user-static # multi-arch build tools
  deploy:
    provider: script
    script: scripts/docker.sh push
# [Job] [Linux]
- name: "Linux"
  os: linux
  before_install:
  - npm install -g npm
# [Job] [OSX]
- name: "OSX"
  os: osx
  osx_image: xcode8.3
  before_install:
  - brew update
  - npm install -g npm

# --------------------------------------------------------------------------------------------------
# Default job settings, when not overwritten by specific jobs.
# --------------------------------------------------------------------------------------------------

dist: trusty
group: travis_latest
os: linux
language: node_js
node_js:
  - "12"

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure: j7SoxNxs3KBRvvLrEWeZGmsgHRLMwcCvYnNh/F8GeaCnM0U87s9AqHMmV4NNRyDoac7PpqegCYk21nLN4mx1Mj9rs/wvQBnl1LYuetRm7ib9Zq21+cJSIaO2USourexEuivySEuzWqR5pb7bcdAZYhKVzBOStw1k0h2rD0xrbdr91UclcQniiex5bqQ4UIE+cPZVqS5vOPZck9P9GMBmVNM0mrfzqTUkiLUFtTbg9Msz5GIIZzJsHj49EqmYwoN1B7te3IkF6tEVLKKNIJPqYMcGhKLZ5jF9ugxkPYPP1JvAxRftrFdCvmdclwJK6yE5ByMY9YHkXw1NvMQ9rzuI10NBM0inUZUmPZepWvnOh4k0FSeFKReWGeVVciap/W0seqxn99lDGMDXaauz5CKD9tVXwAOZ8H/dZAnPEUSd9xEvl5NtLbi1djvvz6LkdDSj9iGedoLEwcxkueBu/UUWLbm+ALdn1dcH1e37TLPc5amP5fIh/klP2KZtfgKzFn8lW65RyrB+UgVlhwQMyv5cCMKAttE1JyU/6bNXvfa0qbnk5m5weVoUsp5PBbx9IYCj7pgGaqmqqON5AOm+JBDK1sl1T2uHCU3wfKBqES8krTPjP7wNiwCTKr7RqyAVYf8d006G6cuDcYIg5NR+l5zM4tfE3U8NHyFrdy0Iw9WBcGg= # DOCKER_EMAIL
    - secure: jc0Y/6EaYofG3QFfoepLxBFW8+Ai8aGWzfME7/afnq1o13zV99SlABm/3VPfiZUJsNAi3/Ji4IqZ5FlkfNT5Gj0C2GWUbSGoi9WURyhxteQQg0b2Bg6JKtaYPRAN1O+BXVHMR8WWS1Xqi6W8dp2xUeZDf8w0VNC4kzAQqhlBV0DQnQjPEMnYGV8FaMDZIYENMRc+T6xjttUPrQHtK2bLhL3xIdZkCauFgX7OcNSBGhGiTDUgO2jgE5si39MCUoU231G3cQnAeBMTXnhYTMENLbwrU2EHJX1btB8lvfnQ4hzeRmgZ7rVUxJ52h7ECGzOyO0QK44q4VMkzU5AtvZ/I7lRVWVb9l+YGaGWk3+zGU2y69hw145stIEjzqByjJJogH9t6g5wmZ/kcl54RMfZvlBdhyyd83zBEnAeSnfzKz4S2AcuAzGaeuIKUMms42SiU+Ixl7m6x0e/kbk4SJ7eP6+GJPtbFUlaXJOEdqa3lANmOqSV8ntXndskuJG+BFrYlpFoBEvJE4fMwO7QRgp/pSiUMO1JVtQ6JT7qSqJYtwWPxfufUrbLkTTohkcqsYICi11ifRYeiVcmJASIWMmWtvSM1IC8wfIEZF8d3mn7Q/1dihhvVzpBbYmY6K9o8/u0T3YKuo+xLwLW+JEpLVx67+MblTP3aF8yDC/WMjWfURrE= # DOCKER_USER
    - secure: HZ5XpBsxlX3ul27m9hyskQ1keT+I/vaxMroREyhXbO+7jgwT8LO9r86+87m2MsUDia4sNF6W/f7VmsOwrJq8K/jbAf8upQERPcyETsib0ElbiVatW1B83rS6T+c5//9NLBXvZcdnUOSEg6PW0B1EDLwpe40ljAZvwpPE362I4Lx9I8DdkcLbzCRIEdH2x7xqpydFsRseieMroWgb6xLlYL5DMOeOpjZ+9L2YSuJaEdGDM2SQmnnrTxKLn1NABo8O5ZeSkOdPvsyT+0x3zHWnS8tvvxdL3awhyR5eRAnhJaqNsNnAUv4uQzvVU+utLJu6KY8BBw//VyKc818ce03gkRzrrBwf8Jk2UE/Ke/9omxP/Iiu4ZGguCmDPeQkA5Gs8D98zWvL0+RvqSmHbatdEsk/74w7HIC0lEV9qF8iG6H3w9ppybNhGxiXVz3jd4k/LsOYakKK7wInEH0p/5sWC6SbWKvnU1VIKedGIJkM/saz2KQuyLuKgZ68tZePET3p0yPxXHsw/bxhaPCZ8jcAWQCh6HbYFBlMUeKnJWlgo7p53MQ88B2rfYiB788SC6gBu4UJl7z7gdtxJPNCypq/jmo6GDhxva0plqgRhYBmNBL2gANsi8qxKSuAyPw7VT36NNoJN48t6SH/Ie0Y2Vja0xRCIzZ1TiOh1dpiLei+EMdA= # DOCKER_PASS
#   - secure: "BAiWc6AblNednsnoh2+3OMW81MVzCQPR0UT3E2/gCdScw8Q9C4a8fC0OpXxJOqHy9JgAL3s5kxZVlAbUhBwXJlarDyQl++Y9aeKjr6J0+iVXu3cSF0cUw+rYbQ41u3dFmF3Sa0K5Lo0uB5XX/ximCX8RzgUJ6B79Jh1ac9FbZrYBth6Ovnsy3Us9VvxB8jXI2St6GJgewmXUo8qlWZKClM79NPBjwpboU09zSGhqQ32JssHUjw/peLt6x4SGV+NsMNgSNELXxVVbBBp7Wp5PNJY8D5vhO703Ka2WLJEebZnE+7r5j1VzLO1/OGrOS9QwVzw/fZEhQYST4NZPMu65bR7VI8jwJN2OjIcUx3yH0JbSXmPtdANofusIozGHKvg7odLTSo3js5crFnDBuoP3ZQ8XNusse2smbyd5snUCb0g9FsEzlQLQZBfcubuW3qY5BZwbCyc2e9WoNOLt4C83rcaFuRER5sK/UG9nSGivIsSKOCJpacdIxmCEvZV8h5YUd/OQqTMbFA2YliaLGt7AsfJrR8W4wy+vB12pVEEg7xPK+TnhzhCK61JGOn/pjVmFjUb0zHgcJEry3C5W+J2TEwKxRIEgkLCL7YP3WnE4c5fcqg2c9B4SHOqReO0KEx5mP0FVlGliW69ZHoUPoEC+VTwVzMJheOTnpzXNh4puh1E=" # GITHUB_TOKEN
#    - secure: "zn6ZQM7LFgFcwFNqcbhBGY9DYZzw3tOa3puTntdcEfnMsp+ikcJSYl8lvTj1TL1rvZIAJfO896Uk79HTyJtv06a9LjpEElaQvkBEtPGnE0fdGWLgK1cl0JBxPNEDicAoYrUV2QkuuwaTtpKeUsnD6XmWSzzpqmZKDLfRyO1xwHyvH4aTvqAhDXM7Hb+Hae4Nk7ZCq5v1CwScu6gdaJMBPdcmWBzAPNnAJYbDilw3fFdfOrxhuTagmmBQFn99iaIRbLR4sTuI/c53NMUS8FJyfistTVVuMOFTSdFvlQ/Ikm6PbIYYIMDp9RetGIJk7IL4U18LpwACzhjc25SvWrQXPI7eiW0H3uD8rGPtR50cBrbxRI/Of7271eqXvtNMzHSsCo0ENQ1qYWoF5OhI4roklAfZjQpdi7Ngg+EPNIgf24vpf0fI9u8caOHxzAYjrwdcXCLTmcu0ANuQMMXP5G7mBZG5/kGzC5cpc11uqwINCU10rVQa7JVNuFNhuT98/c+DSeBY92w9nEsCshG1AKcNjY677FbBdVS+DCPPRjiAfjomT9Ma8VqR/bGCogzaEaA7adUbGLGI9V397QF9gSrzyBP/zjOiYVX1mRjylmEitdQtXF3CXsbhrOOCenDifKHhtnOgXgpObcbwV4B82VhGzDOvTxF2n+QTGhUAA/Okyv8=" # CSC_LINK
#    - secure: "LenBHoTcLW6cF7ML3+dB7JICMzEkawrJHiqFcGSo+hgapB0NCHGUiihr2zrjGSlHmElPiQ2TCnCRmPvOzVfpZswg36D0+1niPgZ+0vfGfPEoPmHhlvIsMPLb7v0lCIeh8z2o9eNbSvnv6NRXS4o5NLlHzM+RhAYARSXvRmFxqCCBn1Sj9pB5TB9NX3mK0Lb3mEJcIgEVFBr/xLiISPUBGFmncHUpxYjZHwxXQXRcGyfOEphLM9tvmEdoILRxM67k035csAIeaLKKPJcMGmO0e/JwZacQN7s3MhD2M8NddhQvWklNjabXAJ0L9Ycujf6rI5RsGcZL2U80HKr0aYRMiVW7/MPMpLARFOUoLfuFAXKkkLHp7Lbb1W6Zftr4yxkrfDXIQsh976HkBj+czr6wGwzBwb39zX4KEm/Yc3TEIxC/kKs9bt+vVW6BG+J41neiDiuIY1D1tRA0OEq0j04zpU6n683ojfYddzFoUWCN+TB3i0HQxWsKTOGKdcQwrJs7xZ4//UzD/vOTHj18SH0nm6ImF2/7q+9wJO646gHWTGTjGFYdupuR402wb3h5vWmGfFRvX6B1QtYImmEwMFnqf2XRwTTSz3niKn2Rt1YUiCP5bEz+Dcr+e+A8Jidt6ZuJEXv5SbykTG4YBmgCuuFT5KRwv08kule7FiUtQ2KD5XE=" # CSC_KEY_PASSWORD


cache:
  directories:
    - $HOME/.electron
    - releases

install: npm install
script:
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      npm run build-latest
    else
      npm run build
    fi
after_success: scripts/bundle-release.sh
addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - gcc-multilib
      - g++-multilib
      - rpm
deploy:
  provider: releases
  token:
    #secure: "nIhLqo+6i/uI0FgneK5nPvzYMEGO0ch7K1kbae/W/DqInqoT+moEAa16vHko3NR4SouICAEuT2GwiP/NdL7V3LZNOBOHmGa9iysBlxH8JU2AgDJiv2daXMTgGmVV7hl2sII5a8utVRFecVjZNJ+EecbU067y9S3gHbsrFlWwdUbLIpVM5+jr0YuXpV949OW8770MKLqvSONL4QoDJD7exNJ77TcHIFZURsr0VSK7rEhCDJhcUzrcn/mXLtVbAJwpBJXPMSj0lObMt1NvaQ6/iQL/rNCv5LYBOhRc0tZaBNRq8xJGR71mA35Vcrt50EP/fFakqdg3n59yO4K26C7GCHEiddlhjFKO1j9ul/98PZ4okw2FBFy1pChNuzme02tguLN85wzKSFERaCbBiNvWvR5MMEWlSuewFKojkbEqSDpZTRvyc6ct/KkvXBr1JXemfH3Uc3ANwNKcuB7566NtN29ogzOJHF/P3OEUy7ny19CZp55kVOKEeCCO3LtubaBwn+S9fP0aKCUC0Q8uHWy1Pfi8iG4XZs+jhPmwj+8OFP4DTBZMR9evk7Iq8/rMYL0WfsDuvbFygyEPWpduJ2YIl31z+7kN0OxQdCwHbNZcxP0n3ieIuNa0K74qfpL6mn0ZaLB1wA7fW/dTc9tF9lMsS577hKGcDwoZPm9VfQ+sVic="
  file_glob: true
  file:
    - "releases/*.*"
  overwrite: true
  on:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on
    tags: false  # Deploy app only when a tag is applied to the commit
    node_js: "12"
